version: "3.9"
services:
  # backend-app:
  #     build: .
  #     depends_on:
  #       - db
  #     environment:
  #       DATABASE_URL: "postgresql://postgres:password@db:5432/mydb?schema=public"

  db:
    env_file:
      - .env
    image: postgres:15
    container_name: postgres_db
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb

    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWD}
      POSTGRES_DB: ${DATABASE_NAME}
    
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_HOSTPORT}:${ADMINER_CONPORT}
    
  backend:
    env_file:
      - .env
    container_name: backend-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run dev"

  frontend:
    container_name: frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  
volumes:
  postgres_data:
