version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb

    ports:
      - "5432:5432"

    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
  adminer:
    image: adminer
    restart: always
    ports:
      - 3080:8080
    
  backend:
    container_name: backend-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    container_name: frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  
volumes:
  postgres_data:
